spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: macbookpro
    password: 19801980
    driver-class-name: org.postgresql.Driver




  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      password: 123

springdoc:
  swagger-ui:
    path: /sw

