spring:
  application:
    name: sotx

  datasource:
    url: jdbc:postgresql://localhost:5432/sotx
    username: macbookpro
    password: 19801980
    driver-class-name: org.postgresql.Driver

  security:
    user:
      password: 123
      name: nosirxon

  jpa:
    hibernate:
      ddl-auto: update



