#example.app-name=Nosirxon
#example.my-skills=java, spring, orm, docker, redis, websocket, spring ai, microservices

example:
  app-name: Nosirxon
  my-skills: java, spring, orm



application:
  prop1:
  prop2:
  prop3:

springdoc:
  swagger-ui:
    path: /sw

